# Generated by Django 5.2.17 on 2026-09-27 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('tutoring_mode', models.CharField(max_length=60)),
                ('messages_count', models.PositiveIntegerField(default=0)),
                ('hints_requested', models.PositiveIntegerField(default=0)),
                ('critical_thinking_score', models.FloatField(default=85.0)),
                ('status', models.CharField(choices=[('Active', 'Active Session'), ('Archived', 'Archived & Saved'), ('Ready', 'Ready for Stage 2 RAG Engine')], default='Ready', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RAGKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=60)),
                ('document_count', models.PositiveIntegerField(default=1)),
                ('chunk_count', models.PositiveIntegerField(default=500)),
                ('vector_engine', models.CharField(default='FAISS / ChromaDB', max_length=40)),
                ('embedding_model', models.CharField(default='all-MiniLM-L6-v2 (SentenceTransformers)', max_length=100)),
                ('is_verified', models.BooleanField(default=True)),
                ('status', models.CharField(default='Synchronized & Indexed', max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('mobile_number', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=120)),
                ('preferred_language', models.CharField(choices=[('Python', 'Python Mentor (Core & Advanced)'), ('SQL', 'SQL & Relational Database Tutor'), ('Java', 'Java & Object-Oriented Programming'), ('DSA', 'Algorithms & Critical Problem Solving'), ('General', 'General Programming Assistant')], default='Python', max_length=40)),
                ('skill_level', models.CharField(choices=[('Beginner', 'Beginner (Starting with Syntax & Fundamentals)'), ('Intermediate', 'Intermediate (Functions, OOP & Query Design)'), ('Advanced', 'Advanced (Architecture, Concurrency & Optimization)')], default='Beginner', max_length=30)),
                ('learning_goal', models.CharField(default='Master programming logic through step-by-step Socratic hints', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutoring_topic', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=5)),
                ('confidence_gain', models.CharField(default='High (+40%)', max_length=50)),
                ('critical_thinking_encouraged', models.BooleanField(default=True)),
                ('feedback_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.chatsession')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='users.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='users.user'),
        ),
    ]
